In [1]:
import numpy as np
import scipy
import matplotlib
import tqdm

In [2]:
import traceback


def green(s):
    return '\033[1;32m%s\033[m' % s


def yellow(s):
    return '\033[1;33m%s\033[m' % s


def red(s):
    return '\033[1;31m%s\033[m' % s


def log(*m):
    print(" ".join(map(str, m)))


def log_exit(*m):
    log(red("ERROR:"), *m)
    exit(1)


def check_numpy():
    try:
        import numpy
        log(green("PASS"), "NumPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "NumPy not installed")


def check_scipy():
    try:
        import scipy
        log(green("PASS"), "SciPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "SciPy not installed")


def check_matplotlib():
    try:
        import matplotlib
        log(green("PASS"), "matplotlib installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "matplotlib not installed")


def check_torch():
    try:
        import torch
        log(green("PASS"), "PyTorch installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "PyTorch not installed")


def check_tqdm():
    try:
        import tqdm
        log(green("PASS"), "tqdm installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "tqdm not installed")


def main():
    try:
        check_numpy()
        check_scipy()
        check_matplotlib()
        check_torch()
        check_tqdm()
    except Exception:
        log_exit(traceback.format_exc())


if __name__ == "__main__":
    main()


PASS NumPy installed
PASS SciPy installed
PASS matplotlib installed
PASS PyTorch installed
PASS tqdm installed


In [3]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    arr=np.random.rand(n,1)
    return arr

In [4]:
z=randomization(4)
print(z)

[[0.27921167]
 [0.39329539]
 [0.87456399]
 [0.93787338]]


In [5]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.rand(h, w)
    B = np.random.rand(h, w)
    s = A+B
    return A,B,s

In [6]:
a,b,c= operations(10, 2)
print(a, '\n\n',b, '\n\n', c)

[[0.37695948 0.25628508]
 [0.98607909 0.46874298]
 [0.68315865 0.45603285]
 [0.08553314 0.12252594]
 [0.40701927 0.60300564]
 [0.75036167 0.16725161]
 [0.61845768 0.43558846]
 [0.8583547  0.29151319]
 [0.97425399 0.75526744]
 [0.25407747 0.05630149]] 

 [[0.7583422  0.36283428]
 [0.7130173  0.04911095]
 [0.28254064 0.79769995]
 [0.56646211 0.99587674]
 [0.52569666 0.56060805]
 [0.9192813  0.33156511]
 [0.71681493 0.65508095]
 [0.38179197 0.99422737]
 [0.09491259 0.90557752]
 [0.51193404 0.37642408]] 

 [[1.13530168 0.61911936]
 [1.69909638 0.51785393]
 [0.96569929 1.25373281]
 [0.65199525 1.11840268]
 [0.93271593 1.16361369]
 [1.66964296 0.49881672]
 [1.33527262 1.09066941]
 [1.24014668 1.28574056]
 [1.06916659 1.66084496]
 [0.76601151 0.43272557]]


In [7]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = np.linalg.norm(A+B)
    return s

In [8]:
a=randomization(3)
b=randomization(3)
norm(a,b)

1.2304023600625782

In [9]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    mul=np.matmul(weights.transpose(),inputs)
    out=np.tanh(mul)
    return out

In [10]:
inputs = np.array([0,0,1])
weights = 2 * np.random.random((3, 1)) - 1
out = neural_network(inputs, weights)

print(out)

[-0.53336389]


In [11]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if(x<y):
        return x*y
    else:
        return x/y

In [12]:
scalar_function(2,5)

10

In [13]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y
    """
    out = np.vectorize(scalar_function)
    return out(x,y)

In [14]:
vector_function(4,5)

array(20)